org.gradle.jvmargs=-Xmx6G
base_version=19.0
unstable=false
supported_version=1.21.5
minecraft_version=1.21.5
platforms=fabric,neoforge
forge_version=49.1.10
neoforge_version=21.5.23-beta
neoforge_pr=
fabricloader_version=0.16.12
cloth_config_version=18.0.145
modmenu_version=11.0.0-rc.2
fabric_api=0.119.6+1.21.5
architectury_version=16.1.4
api_exculde=
#api_include=me.shedaniel.cloth:cloth-events,me.shedaniel.cloth:config-2,me.sargunvohra.mcmods:autoconfig1u,org.jetbrains:annotations,net.fabricmc.fabric-api:fabric
