org.gradle.jvmargs=-Xmx6G
base_version=26.3
unstable=false
supported_version=26.3
minecraft_version=26.3
platforms=fabric,neoforge
forge_version=49.1.10
neoforge_version=26.3.0.33-beta
neoforge_pr=
fabricloader_version=0.19.5
cloth_config_version=26.3.159
modmenu_version=22.0.0-alpha.1
fabric_api=0.161.0+26.3
architectury_version=22.0.3
api_exculde=
#api_include=me.shedaniel.cloth:cloth-events,me.shedaniel.cloth:config-2,me.sargunvohra.mcmods:autoconfig1u,org.jetbrains:annotations,net.fabricmc.fabric-api:fabric
