org.gradle.jvmargs=-Xmx6G
base_version=26.1
unstable=false
supported_version=26.1.2
minecraft_version=26.1.2
platforms=fabric,neoforge
forge_version=49.1.10
neoforge_version=26.1.2.76
neoforge_pr=
fabricloader_version=0.19.2
cloth_config_version=26.1.154
modmenu_version=17.0.0-alpha.1
fabric_api=0.150.0+26.1.2
architectury_version=20.0.6
api_exculde=
#api_include=me.shedaniel.cloth:cloth-events,me.shedaniel.cloth:config-2,me.sargunvohra.mcmods:autoconfig1u,org.jetbrains:annotations,net.fabricmc.fabric-api:fabric
