pluginManagement {
    repositories {
        maven { url "https://maven.shedaniel.me/" }
        maven { url "https://maven.fabricmc.net/" }
        gradlePluginPortal()
        maven { url "https://files.minecraftforge.net/maven/" }
    }
}

if (JavaVersion.current().ordinal() + 1 < 21) {
    throw new IllegalStateException("Please run gradle with Java 21+!")
}

rootProject.name = "RoughlyEnoughItems"

include "api"
include "default-plugin"
include "runtime"
include "fabric"
//include "forge"
include "neoforge"
