pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.shedaniel.me/" }
        maven { url "https://maven.architectury.dev/" }
        gradlePluginPortal()
    }
}

if (JavaVersion.current().ordinal() + 1 < 25) {
    throw new IllegalStateException("Please run gradle with Java 25+!")
}

rootProject.name = "RoughlyEnoughItems"
