base {
    archivesName = rootProject.name + "-" + project.name
}

loom {
    accessWidenerPath = gradle.rootProject.project("fabric").file("src/main/resources/roughlyenoughitems.accessWidener")
}

dependencies {
    compileOnly("net.fabricmc:fabric-loader:${project.fabricloader_version}")
    api("me.shedaniel.cloth:cloth-config:${cloth_config_version}")
    api("dev.architectury:architectury:${architectury_version}")
}

architectury {
    common(platforms.split(","))
}

task fakeJar(type: Jar, dependsOn: jar) {
    from jar.archiveFile.map { zipTree(it) }
    from(rootProject.file("fake/fabric.mod.json")) {
        into ""
    }
    archiveClassifier = "fake"
}

task fakeForgeJar(type: Jar, dependsOn: jar) {
    from jar.archiveFile.map { zipTree(it) }
    from(rootProject.file("fake/mods.toml")) {
        into "META-INF"
    }
    ["REIPlugin", "REIPluginClient", "REIPluginCommon", "REIPluginDedicatedServer",
     "REIPluginLoader", "REIPluginLoaderClient", "REIPluginLoaderCommon", "REIPluginLoaderDedicatedServer"].each {
        from(rootProject.file("fake/${it}.class")) {
            into "me/shedaniel/rei/forge"
        }
    }
    archiveClassifier = "fake-forge"
}

def productionJar = tasks.register("productionJar", Jar) {
    dependsOn tasks.named("jar")
    from { zipTree(tasks.named("jar").flatMap { it.archiveFile }) }
    archiveClassifier = ""
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.name + "-" + project.name
            artifact(productionJar)
            artifact(tasks.named("sourcesJar")) {
                classifier = "sources"
            }
            pom.withXml {
                def depsNode = asNode().appendNode("dependencies")
                configurations.api.allDependencies.each { dep ->
                    if (dep.group != null && dep.version != null) {
                        def d = depsNode.appendNode("dependency")
                        d.appendNode("groupId", dep.group)
                        d.appendNode("artifactId", dep.name)
                        d.appendNode("version", dep.version)
                        d.appendNode("scope", "compile")
                    }
                }
            }
        }
    }
}
